### ISSUE TITLE
RSS feed HTML formatering

### ISSUE THREAD

**Issue by benjaoming** [ronan-mch/duk_op#332]
There's HTML formatting missing on the strings in description of events... maybe the same HTML as on the event detail page could appear?

![screenshot from 2016-03-15 16 50 49](https://cloud.githubusercontent.com/assets/374612/13782036/26e52808-eace-11e5-841a-537dea9cb1d7.png)

**Comment by ronan-mch** [comment]
Jeg har bevidst undladt at lægge HTML formattering ind, da jeg forstod fra @biveke at det helst skulle være så rå som muligt. Der er *meget* diskussion om emnet på #291.

**Comment by biveke** [comment]
Ronan, det var nu mest for at spare dig for hovedpine. Du må såmænd gerne forsøge dig med html-formattering, selvom det måske kan blive lidt problematisk... Det er bare overhovedet ikke et krav. Jeg tænker, at det kan blive lidt svært

**Comment by ronan-mch** [comment]
det er ikke svært for mig at tilføj lidt html struktur, det kunne måske
også hjælpe med præsentationen af kalenderen på jeres side...

2016-03-15 20:36 GMT+01:00 biveke <notifications@github.com>:

**Comment by biveke** [comment]
Det ville være superfedt!

**Comment by benjaoming** [comment]
Fixed in 0096ed6
