### ISSUE TITLE
Faste begivenheder knappen flyver på mobil

### ISSUE THREAD

**Issue by Siggik** [ronan-mch/duk_op#351]
kan ikke finde ud at tage screenshot på mobilen.  Men måke kan den blive rykket på plads og omdøbes til Se faste begivenheder.

**Comment by dotnetCarpenter** [comment]
@Siggik Screenshot på mobil.
Til Android
>For the vast majority of Android phones and tablets, to take a screenshot you simply press and hold the power and volume-down buttons together. There is a slight knack to this action: press the power button too soon and the display will switch off; press the volume-down button too soon and your screenshot may be marred by an onscreen volume slider. After a few seconds the screen will flash and a notification will appear in the drop-down bar at the top of the screen, giving you options to delete, share or edit the image. You can also access the screenshot from your Gallery.
> http://www.pcadvisor.co.uk/how-to/google-android/how-take-screenshot-on-android-phones-tablets-summary-windows-ios-android-3623449/

Til iPhone:
>Press and hold the Sleep/Wake button on the top or side of your iPhone, iPad, or iPod touch, then immediately press and release the Home button.
>
>You can find the screenshot in your Photos app.
> https://support.apple.com/en-us/HT200289

**Comment by Siggik** [comment]
ok, så fadnt jeg ud af det med billedet. Men min brøwser har en eller sikkerheds feature som gør at den ikke vil tages billeder af. Sejt, men lidt besværlgit nu. Kan @tadoh tage et screenshot?

**Comment by tadoh** [comment]
![screenshot_2016-05-22-23-35-55](https://cloud.githubusercontent.com/assets/7386049/15456616/0a906446-2076-11e6-80d6-a72fe1005fb7.png)

Ved ikke om det er det her, du mener?

**Comment by Siggik** [comment]
ja, præcis. Det ser skørt ud, right?

**Comment by benjaoming** [comment]
Nyt layout på vej, vi har været elendige til at fikse de her små ting, men lad os teste det nye layout grundigt på mobil og sørge for, at det her holder op med at være et problem.
