### ISSUE TITLE
ny eller nyt event?

### ISSUE THREAD

**Issue by Siggik** [ronan-mch/duk_op#356]
Lige ny hedder det ny event. Er det ikke sprogligt skørt? Jeg ville sige Nyt event. I følge denne orbog kan det både være et eller en foran: http://ordnet.dk/ddo/ordbog?query=event Jeg kan klart bedst lige Nyt og ikke ny. Ny lyder somen parodi i mine øre. @benjaoming ,

**Comment by benjaoming** [comment]
Jeg kan desværre ikke sige, at jeg synes den ene eller den anden lyder bedst, men hvis _du_ synes det, så er det _for real_ :) Evt. prøv at spørge nogle andre hurtigt, hvad de synes.

**Comment by Siggik** [comment]
hvad siger i andre: @ronan-mch , @larsgaardsoe @tadoh @waffle-iron ?

**Comment by tadoh** [comment]
Jeg kokser 50% af en og et alligevel :)

**Comment by benjaoming** [comment]
Det er lige meget :P

http://ordnet.dk/ddo/ordbog?query=event&tab=for
