### ISSUE TITLE
Hidden events via RSS

### ISSUE THREAD

**Issue by tadoh** [ronan-mch/duk_op#362]
Still RSS for IF - but I think more groups that organise broader than Copenhagen could benefit from it perhaps.

Right now we have a feature that allows a user to hide the event from the homepage. The event does not show up on the user page either. If it did show up, a group that has activities that are not relevant for Copenhagen, or even internal meetings, could use the feature and export via RSS to their own homepage.

This arises from IF's current situation: IF Copenhagen uses Duk Op and events are pulled from Duk Op into the homepage. However the rest of the organisation does not use it because they for instance live in Jutland, and their calendar appears at the side of the one pulled from Duk Op. It looks silly on IF's page, and it might end in the whole of IF dropping Duk Op in favour of just creating events on their homepage.

I imagine this would be a viable solution in terms of not requireing too much work to implement (it's almost already there), it would be still hide events from the homepage but would make it easier for groups to adopt Duk Op as their standard practice to the import into the homepage. If this gets implemented and Duk Op RSS smooth, we can also begin to advertise for this possibility and attract more groups to the calendar that way.

Your thoughts on this?

**Comment by Siggik** [comment]
I think it sounds like a great idea!

**Comment by ronan-mch** [comment]
that should be trivial to implement.

**Comment by ronan-mch** [comment]
should be there now, test and make sure you're happy.

**Comment by Siggik** [comment]
Cool, er den oppw På test siden eller også den rigtige?

**Comment by ronan-mch** [comment]
Prod

Den ons. 22. jun. 2016 22.52 skrev Siggik <notifications@github.com>:

**Comment by Siggik** [comment]
Det ser ud til at virke perfekt!

**Comment by Siggik** [comment]
how, en overvejelse: Lige nu er de synelige på brugerprofil siderne, når den ikke er promeveret. Skal den evt. også være synlig på lokationsiderne?

F.eks. bruge Folkets Hus lokationer siden og ikke profil siden at henvise folk til, da alle så ikke skal bruge samme profil til at oprette events. Hvad tænker I? @tadoh  @ronan-mch ?

**Comment by tadoh** [comment]
God ide. Tror det er forskelligt om folk trækker rss fra bruger eller stedet, men det giver mening uanset hvad. Dog synes jeg at eventet by default skal være synlig.

-------- Original message --------

**Comment by ronan-mch** [comment]
Jeg undersøgte lige hvorvidt RSS bliver brugt. I dagens log kan jeg se at den blev anvendt 118 gange:

```bash
grep rss unicorn.log | awk '{ print $4 }' | sed 's/controller=//g' | sort | uniq -c
     77 locations
     41 user
```

**Comment by Siggik** [comment]
Det er da ret vildt. Det blir brugt meget mere end jeg ville have troet! Hvad dækker tallene over? 

Jeg kan selv ikke see muligheden for at vælge rss i min browser. Vorews brugere er klogere end mig? :)

**Comment by ronan-mch** [comment]
Firefox har fjernet RSS knappen som default, men du kan vist godt tilføje
den igen ind i dine indstillinger.

**Comment by Siggik** [comment]
Så fandt jeg det. Ikke ligfrem brugervenligt i min iceweasel udgave. Gætter på at det er mere brugervenligt i andre browsere, når nu så mange har brugt det. 

...Eller nu, kiggede jeg lige listen igennem. Der er næsten ikke nogle gengangere? Lugter det ikke lidt af, at det er en person eller nogle få der har valft at abonnomre på en lang rækkesteder og users?

Jeg er stadig pro at sætte en rss knap ind under navnet på stedet/lokationen ug over beskrivelsen på deres sider? Hvad tænker du?

**Comment by ronan-mch** [comment]
Der er ikke gengangere fordi jeg har talt dem og sorterede efter hyppighed.
Men alligevel er det underlige ting der står øverst. f.eks. Nørrebrohallen
frem for de mere oplagt som Folkets Hus.

2016-07-06 11:20 GMT+02:00 Siggik <notifications@github.com>:

**Comment by Siggik** [comment]
Ahh, I see, kan du huske hvem de andre øverste er?

**Comment by ronan-mch** [comment]
slå det op din dovne hund.

**Comment by Siggik** [comment]
Ja, men det var nemmere hvis du kunne huske det:)

**Comment by ronan-mch** [comment]
ha, men du savner tydeligvis en overspringshandling!

**Comment by Siggik** [comment]
ja, jeg tager bare lidt tilløb, opgaven skal også skrives:)

**Comment by Siggik** [comment]
Dum opgave, hurra for overspringshandling: 

7 x Nørrebrohallen
6x Verdenskademiet
6x BolsjeFabrikken
6x somewhere in Nørrebro
4x Normstormerne
4x Annelise Witek
3x Internationalt Forum
3x BjoernoB
3x Underwerket

Her er de rss sider med mere en 2 abonomenter. En ret random liste?

**Comment by benjaoming** [comment]
Robot-agtige benjaoming lukker lige den her issue
