### ISSUE TITLE
Grafic glitch (same as old)

### ISSUE THREAD

**Issue by tadoh** [ronan-mch/duk_op#381]
På en Mac med Safari.
Tags flytter sig når kommer over den linje, der deler spotlight events og resten

![skaermbillede 2016-10-07 kl 09 54 29](https://cloud.githubusercontent.com/assets/7386049/19182586/3c33cb22-8c74-11e6-9f2e-29abf785143f.png)

**Comment by benjaoming** [comment]
VI HAR SVIGTET!!!§

Men nu er det også lige meget, for der kommer nyt design *phew*
