### ISSUE TITLE
nyt logo

### ISSUE THREAD

**Issue by Siggik** [ronan-mch/duk_op#387]
Nyt logo med store bogstaver til forsiden:
![logo](https://cloud.githubusercontent.com/assets/7570153/20648321/ba45998a-b4a3-11e6-8442-fddb72cafe84.jpg)

**Comment by tadoh** [comment]
Flot - men det gamle er også flot...?


Den 27-11-2016 kl. 13:17 skrev Siggik:

**Comment by Siggik** [comment]
ja, eller nej, jeg synes det er kikset med små bogstaver?

**Comment by benjaoming** [comment]
Jeg kan bedre lide farven og tydeligheden på det nye, men det er ikke enkelt at passe logoet ind, da det er mere kvadratisk. Så skal man ændre i layout. Men det er vigtigt, at forsiden er enormt funktionel, så man altid hurtigt kan se arrangementerne.. var der noget særligt, du havde tænkt på @Siggik ?
![screenshot from 2016-12-25 14-08-32](https://cloud.githubusercontent.com/assets/374612/21471269/3fb096c4-caac-11e6-9f1c-6b548a71f985.png)

**Comment by Siggik** [comment]
ja, det er god pointe. Det gamles rodnet, har jeg ikke adgang til. Ville det virker, hvis jeg bare laver rodnettet kortere i venstreside, eller er det stadig for langt?

**Comment by benjaoming** [comment]
@Siggik ja, det ville være bedre, hvis rodnettet var kortere / fladere.. så hele logoets højde:bredde forhold er mere aflangt.

**Comment by benjaoming** [comment]
OK, lukker den her pga. redesign.
