### ISSUE TITLE
Export to personal calendar

### ISSUE THREAD

**Issue by Siggik** [ronan-mch/duk_op#396]
We need to export events to personal calendars. Research and implement the best method to do this.

**Comment by Siggik** [comment]
Please use the presenter pattern in implementing this, so all the view logic can be encapsulated at this level. API should be `presenter.ics_tags`. See the [implementation here](https://github.com/ronan-mch/det_sker/blob/master/app/presenters/event_presenter.rb).

**Comment by benjaoming** [comment]
This was done in #410 which was copy-paste merged in 34b18c5
